/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2019-08-30 02:37:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.bbs;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class paging_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

int totalRecordCount; 	// 전체 글 수	(23 -> 3페이지)
int pageNumber;			// 현재 페이지 0~9	== [1]~[10]
int pageCountPerScreen;	// 스크린당 페이지 수 	[1][2][3][4][5][6][7][8][9][10] >>	=10
int recordCountPerPage; // 페이지당 글 수	= 10

String st1 = request.getParameter("totalRecordCount");	// 총 글 수는 db에서 꺼내와야 됨
if(st1 == null)	totalRecordCount = 0;
else 			totalRecordCount = Integer.parseInt(st1);

String st2 = request.getParameter("pageNumber");
if(st2 == null)	pageNumber = 0;
else 			pageNumber = Integer.parseInt(st2);

String st3 = request.getParameter("pageCountPerScreen");
if(st3 == null)	pageCountPerScreen = 0;
else 			pageCountPerScreen = Integer.parseInt(st3);

String st4 = request.getParameter("recordCountPerPage");
if(st4 == null)	recordCountPerPage = 0;
else 			recordCountPerPage = Integer.parseInt(st4);

// 총 페이지 수
int totalPageCount = totalRecordCount / recordCountPerPage;
//		2					23					10

if((totalRecordCount % recordCountPerPage)!=0){	// 남은 페이지가 있으면
		totalPageCount++;		// -> 3
}

// 					0	10		20 으로 나오는데 화면에 보일땐 1씩 올려서 보여준다.
// view에서 시작 페이지[1]	[11]	[21] ..		<<[1][2][3]...[10]>>
int screenStartPageIndex = ((pageNumber + 1) / pageCountPerScreen)*pageCountPerScreen;
//		0						((0+1)		/		10)*				0

// 끝페이지  [10] [20] [30]
int screenEndPageIndex = (((pageNumber + 1) / pageCountPerScreen)*pageCountPerScreen) + pageCountPerScreen;

// 끝페이지는 다시 계산
if(screenEndPageIndex > totalPageCount){		// 총 페이지보다 끝페이지가 크면
	screenEndPageIndex = totalPageCount;
}

if((pageNumber + 1)%pageCountPerScreen == 0){
	screenStartPageIndex = (((pageNumber+1) / pageCountPerScreen)*pageCountPerScreen)-pageCountPerScreen;
	
	screenEndPageIndex = pageNumber + 1;		// 0 -> 1	, 9-> 10
}



      out.write("\r\n");
      out.write("<div style=\"float: left; width: 96%; text-align: center;\">\r\n");
      out.write("\t<!-- << -->\r\n");
      out.write("\t<a href=\"#none\" title=\"처음페이지\" onclick=\"goPage('0')\">\r\n");
      out.write("\t\t<img alt=\"\" src=\"image/arrow_first.gif\" style=\"width: 9px; height: 9px\">\r\n");
      out.write("\t</a>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- < -->\r\n");
      out.write("\t");

	if(screenStartPageIndex > 1){
		
      out.write("\r\n");
      out.write("\t\t<a href=\"#none\" title=\"이전페이지\" onclick=\"goPage('");
      out.print(screenStartPageIndex-1 );
      out.write("')\">\r\n");
      out.write("\t\t\t<img alt=\"\" src=\"image/arrow_back.gif\" style=\"width: 9px; height: 9px\">\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t");

	}
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- [1] 2 [3] -->\r\n");
      out.write("\t");

	for(int i = screenStartPageIndex; i < screenEndPageIndex; i++){
		if(i == pageNumber){	// 현재 페이지
			
      out.write("\r\n");
      out.write("\t\t\t<span style=\"font-size: 9pt; color: #000000; font-weight: bold;\">\r\n");
      out.write("\t\t\t\t");
      out.print(i+1 );
      out.write("\r\n");
      out.write("\t\t\t</span>\r\n");
      out.write("\t\t\t");

		}else{		// 그외의 페이지들
			
      out.write("\r\n");
      out.write("\t\t\t<a href=\"#none\" title=\"");
      out.print(i+1 );
      out.write("페이지\" onclick=\"goPage(");
      out.print(i );
      out.write(")\"\t\r\n");
      out.write("\t\t\t\tstyle=\"font-size: 7.5pt; color: #000000; font-weight: normal;\" id=\"_clickPage\">\r\n");
      out.write("\t\t\t\t[");
      out.print(i+1 );
      out.write("]\r\n");
      out.write("\t\t\t</a>\t\r\n");
      out.write("\t\t\t");
	
		}
	}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- > -->\r\n");
      out.write("\t");

	if(screenEndPageIndex < totalPageCount){	//  [11][12][13] >
		
      out.write("\r\n");
      out.write("\t\t<a href=\"#none\" title=\"다음페이지\" onclick=\"goPage(");
      out.print(screenEndPageIndex );
      out.write(")\">\r\n");
      out.write("\t\t\t<img alt=\"\" src=\"image/arrow_next.gif\" style=\"width: 9px; height: 9px\">\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t");
	
	}	
	int end_page = 0;
	if(totalPageCount > 0){
		end_page = totalPageCount - 1;	
	}
	
	//		[1][2][3]
	//		[11][12][13]
	//		총페이지 -> 120		
	
	
      out.write("\r\n");
      out.write("\t<!-- >> -->\r\n");
      out.write("\t<a href=\"#none\" title=\"마지막페이지\" onclick=\"goPage(");
      out.print(end_page );
      out.write(")\">\r\n");
      out.write("\t\t<img alt=\"\" src=\"image/arrow_end.gif\" style=\"width: 9px; height: 9px\">\r\n");
      out.write("\t</a>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
